spring.application.name=inventory-service
server.port=8091

spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_db
spring.datasource.username=postgres
spring.datasource.password=Sin0602
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=inventory-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties[spring.json.value.default.type]=org.example.inventoryservice.event.OrderEvent
spring.kafka.consumer.properties[spring.json.trusted.packages]=org.example.inventoryservice.event
spring.kafka.consumer.properties[spring.json.use.type.headers]=false